**Pitfalls and A few PyTorch conventions:**

1.   mark variables with requires_grad=True
2.   clear w.grad each iteration
3.   update parameters under torch.no_grad()

The main steps of a PyTorch training loop are:
*   Prepare a batch of samples from the training set. You can use a DataLoader for this.
*   Optionally transfer these samples to the GPU (typically using X_batch.to(device) and y_batch.to(device)).
* Run the inputs through the model, for example y_pred = model(X_batch).
* Compute the loss, for example loss = criterion(y_pred, y_true).
* Backpropagate through the loss using loss.backward().
* Perform an optimizer step: optimizer.step().
* Zero out the gradients: optimizer.zero_grad() (alternatively, you can do this before the backward pass, which may be safer if the gradients are non-zero before the training loop starts).

In [1]:
import torchvision
import numpy as np
import torch
import torch.nn as nn
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from torchvision import transforms


image_path = './'
transform = transforms.Compose([transforms.ToTensor()])

mnist_train_dataset = torchvision.datasets.MNIST(root=image_path,
                                           train=True,
                                           transform=transform,
                                           download=True)
mnist_test_dataset = torchvision.datasets.MNIST(root=image_path,
                                           train=False,
                                           transform=transform,
                                           download=False)

batch_size = 64
torch.manual_seed(1)
train_dl = DataLoader(mnist_train_dataset, batch_size, shuffle=True)

100%|██████████| 9.91M/9.91M [00:00<00:00, 42.7MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.20MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 10.5MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 7.90MB/s]

In [2]:
hidden_units = [32, 16]
image_size = mnist_train_dataset[0][0].shape
input_size = image_size[0] * image_size[1] * image_size[2]

all_layers = [nn.Flatten()]
for hidden_unit in hidden_units:
    layer = nn.Linear(input_size, hidden_unit)
    all_layers.append(layer)
    all_layers.append(nn.ReLU())
    input_size = hidden_unit

all_layers.append(nn.Linear(hidden_units[-1], 10))
model = nn.Sequential(*all_layers)

model

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=784, out_features=32, bias=True)
  (2): ReLU()
  (3): Linear(in_features=32, out_features=16, bias=True)
  (4): ReLU()
  (5): Linear(in_features=16, out_features=10, bias=True)
)

In [3]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Trainable parameters: {num_params}")

Trainable parameters: 25818

In [60]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

torch.manual_seed(1)
num_epochs = 20
for epoch in range(num_epochs):
    accuracy_hist_train = 0
    for x_batch, y_batch in train_dl:
        x_batch = x_batch.to(device)
        y_batch = y_batch.to(device)
        pred = model(x_batch)
        loss = loss_fn(pred, y_batch)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        is_correct = (torch.argmax(pred, dim=1) == y_batch).float()
        accuracy_hist_train += is_correct.sum()
    accuracy_hist_train /= len(train_dl.dataset)
    print(f'Epoch {epoch}  Accuracy {accuracy_hist_train:.4f}')

Epoch 0  Accuracy 0.8531
Epoch 1  Accuracy 0.9287
Epoch 2  Accuracy 0.9413
Epoch 3  Accuracy 0.9506
Epoch 4  Accuracy 0.9558
Epoch 5  Accuracy 0.9592
Epoch 6  Accuracy 0.9627
Epoch 7  Accuracy 0.9649
Epoch 8  Accuracy 0.9673
Epoch 9  Accuracy 0.9690
Epoch 10  Accuracy 0.9711
Epoch 11  Accuracy 0.9729
Epoch 12  Accuracy 0.9737
Epoch 13  Accuracy 0.9747
Epoch 14  Accuracy 0.9766
Epoch 15  Accuracy 0.9778
Epoch 16  Accuracy 0.9780
Epoch 17  Accuracy 0.9798
Epoch 18  Accuracy 0.9806
Epoch 19  Accuracy 0.9816

In [15]:
device

device(type='cpu')

In [16]:
torch.cuda.is_available()

False

In [61]:
import pandas as pd

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Origin']

df = pd.read_csv(url, names=column_names,
                 na_values = "?", comment='\t',
                 sep=" ", skipinitialspace=True)

df.tail()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin
393,27.0,4,140.0,86.0,2790.0,15.6,82,1
394,44.0,4,97.0,52.0,2130.0,24.6,82,2
395,32.0,4,135.0,84.0,2295.0,11.6,82,1
396,28.0,4,120.0,79.0,2625.0,18.6,82,1
397,31.0,4,119.0,82.0,2720.0,19.4,82,1

In [62]:
print(df.isna().sum())

df = df.dropna()
df = df.reset_index(drop=True)
df.tail()

MPG             0
Cylinders       0
Displacement    0
Horsepower      6
Weight          0
Acceleration    0
Model Year      0
Origin          0
dtype: int64

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin
387,27.0,4,140.0,86.0,2790.0,15.6,82,1
388,44.0,4,97.0,52.0,2130.0,24.6,82,2
389,32.0,4,135.0,84.0,2295.0,11.6,82,1
390,28.0,4,120.0,79.0,2625.0,18.6,82,1
391,31.0,4,119.0,82.0,2720.0,19.4,82,1

In [63]:
import sklearn
import sklearn.model_selection


df_train, df_test = sklearn.model_selection.train_test_split(df, train_size=0.8, random_state=1)
train_stats = df_train.describe().transpose()
train_stats

,count,mean,std,min,25%,50%,75%,max
MPG,313.0,23.404153,7.666909,9.0,17.5,23.0,29.0,46.6
Cylinders,313.0,5.402556,1.701506,3.0,4.0,4.0,8.0,8.0
Displacement,313.0,189.512780,102.675646,68.0,104.0,140.0,260.0,455.0
Horsepower,313.0,102.929712,37.919046,46.0,75.0,92.0,120.0,230.0
Weight,313.0,2961.198083,848.602146,1613.0,2219.0,2755.0,3574.0,5140.0
Acceleration,313.0,15.704473,2.725399,8.5,14.0,15.5,17.3,24.8
Model Year,313.0,75.929712,3.675305,70.0,73.0,76.0,79.0,82.0
Origin,313.0,1.591054,0.807923,1.0,1.0,1.0,2.0,3.0

In [64]:
from packaging import version


numeric_column_names = ['Cylinders', 'Displacement', 'Horsepower', 'Weight', 'Acceleration']

df_train_norm, df_test_norm = df_train.copy(), df_test.copy()


if version.parse(pd.__version__) >= version.parse("2.0.0"):

    for col_name in numeric_column_names:
        mean = train_stats.loc[col_name, 'mean']
        std = train_stats.loc[col_name, 'std']
        df_train_norm[col_name] = (df_train_norm[col_name] - mean) / std
        df_test_norm[col_name] = (df_test_norm[col_name] - mean) / std

else:

    for col_name in numeric_column_names:
        mean = train_stats.loc[col_name, 'mean']
        std  = train_stats.loc[col_name, 'std']
        df_train_norm.loc[:, col_name] = (df_train_norm.loc[:, col_name] - mean) / std
        df_test_norm.loc[:, col_name] = (df_test_norm.loc[:, col_name] - mean) / std

df_train_norm.tail()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin
203,28.0,-0.824303,-0.901020,-0.736562,-0.950031,0.255202,76,3
255,19.4,0.351127,0.413800,-0.340982,0.293190,0.548737,78,1
72,13.0,1.526556,1.144256,0.713897,1.339617,-0.625403,72,1
235,30.5,-0.824303,-0.891280,-1.053025,-1.072585,0.475353,77,1
37,14.0,1.526556,1.563051,1.636916,1.470420,-1.359240,71,1

In [65]:
boundaries = torch.tensor([73, 76, 79])

v = torch.tensor(df_train_norm['Model Year'].values)
df_train_norm['Model Year Bucketed'] = torch.bucketize(v, boundaries, right=True)

v = torch.tensor(df_test_norm['Model Year'].values)
df_test_norm['Model Year Bucketed'] = torch.bucketize(v, boundaries, right=True)

numeric_column_names.append('Model Year Bucketed')

In [66]:
from torch.nn.functional import one_hot


total_origin = len(set(df_train_norm['Origin']))

origin_encoded = one_hot(torch.from_numpy(df_train_norm['Origin'].values) % total_origin)
x_train_numeric = torch.tensor(df_train_norm[numeric_column_names].values)
x_train = torch.cat([x_train_numeric, origin_encoded], 1).float()

origin_encoded = one_hot(torch.from_numpy(df_test_norm['Origin'].values) % total_origin)
x_test_numeric = torch.tensor(df_test_norm[numeric_column_names].values)
x_test = torch.cat([x_test_numeric, origin_encoded], 1).float()
y_train = torch.tensor(df_train_norm['MPG'].values).float()
y_test = torch.tensor(df_test_norm['MPG'].values).float()

In [67]:
x_train.shape

torch.Size([313, 9])

In [68]:
x_test.shape

torch.Size([79, 9])

In [69]:
y_train = torch.tensor(df_train_norm['MPG'].values).float()
y_test = torch.tensor(df_test_norm['MPG'].values).float()

In [70]:
y_train.shape

torch.Size([313])

In [71]:
y_test.shape

torch.Size([79])

In [72]:
from torch.utils.data import DataLoader, TensorDataset


train_ds = TensorDataset(x_train, y_train)
batch_size = 8
torch.manual_seed(1)
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [73]:
hidden_units = [8, 4]
input_size = x_train.shape[1]

all_layers = []
for hidden_unit in hidden_units:
    layer = nn.Linear(input_size, hidden_unit)
    all_layers.append(layer)
    all_layers.append(nn.ReLU())
    input_size = hidden_unit

all_layers.append(nn.Linear(hidden_units[-1], 1))

model = nn.Sequential(*all_layers)

In [74]:
model

Sequential(
  (0): Linear(in_features=9, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=4, bias=True)
  (3): ReLU()
  (4): Linear(in_features=4, out_features=1, bias=True)
)

In [75]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Trainable parameters: {num_params}")

Trainable parameters: 121

In [76]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

In [77]:
torch.manual_seed(1)
num_epochs = 200
log_epochs = 20
for epoch in range(num_epochs):
    loss_hist_train = 0
    for x_batch, y_batch in train_dl:
        x_batch = x_batch.float()
        y_batch = y_batch.float()
        pred = model(x_batch)[:, 0]
        loss = loss_fn(pred, y_batch)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        loss_hist_train += loss.item()
    if epoch % log_epochs==0:
        print(f'Epoch {epoch}  Loss {loss_hist_train/len(train_dl):.4f}')

Epoch 0  Loss 536.1047
Epoch 20  Loss 8.4361
Epoch 40  Loss 7.8695
Epoch 60  Loss 7.1891
Epoch 80  Loss 6.7062
Epoch 100  Loss 6.7599
Epoch 120  Loss 6.3124
Epoch 140  Loss 6.6864
Epoch 160  Loss 6.7648
Epoch 180  Loss 6.2156

In [78]:
with torch.no_grad():
    pred = model(x_test.float())[:, 0]
    loss = loss_fn(pred, y_test)
    print(f'Test MSE: {loss.item():.4f}')
    print(f'Test MAE: {nn.L1Loss()(pred, y_test).item():.4f}')

Test MSE: 9.6133
Test MAE: 2.1211

In [4]:
import torchvision
import numpy as np
import torch
import torch.nn as nn
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from torchvision import transforms

from sklearn.datasets import fetch_covtype
from torch.utils.data import TensorDataset

covtype = fetch_covtype()

X_covtype = torch.tensor(covtype.data, dtype=torch.float32)
means = X_covtype.mean(dim=0, keepdim=True)
stds = X_covtype.std(dim=0, keepdim=True)
X_standardized_covtype = (X_covtype - means) / stds

y_covtype = torch.tensor(covtype.target - 1, dtype=torch.long)

covtype_dataset = TensorDataset(X_standardized_covtype, y_covtype)

In [5]:
from torch.utils.data import random_split

torch.manual_seed(42)

train_size = len(covtype_dataset) * 80 // 100
valid_size = len(covtype_dataset) * 10 // 100
test_size = len(covtype_dataset) - train_size - valid_size

train_dataset, valid_dataset, test_dataset = random_split(
    covtype_dataset,
    [train_size, valid_size, test_size])

In [6]:
from torch.utils.data import DataLoader

batch_size = 256

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=batch_size)
test_loader = DataLoader(test_dataset, batch_size=batch_size)

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
n_inputs = len(covtype.feature_names)  # == 54
n_classes = len(set(covtype.target))  # == 7

torch.manual_seed(42)
covtype_model = nn.Sequential(
    nn.Linear(n_inputs, 200), nn.ReLU(),
    nn.Linear(200, 100), nn.ReLU(),
    nn.Linear(100, 50), nn.ReLU(),
    nn.Linear(50, n_classes)
).to(device)

In [8]:
import torchmetrics

ModuleNotFoundError: No module named 'torchmetrics'

In [9]:
pip install torchmetrics

Collecting torchmetrics
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.0.2)
Requirement already satisfied: packaging>17.1 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (26.0)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.10.0+cpu)
Collecting lightning-utilities>=0.15.3 (from torchmetrics)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from lightning-utilities>=0.15.3->torchmetrics) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.25.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->torchmetrics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->torchmetrics) (3.0.3)
Downloading torchmetrics-1.9.0-py3-none-any.whl (983 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 17.2 MB/s eta 0:00:00
Downloading lightning_utilities-0.15.3-py3-none-any.whl (31 kB)
Installing collected packages: lightning-utilities, torchmetrics
Successfully installed lightning-utilities-0.15.3 torchmetrics-1.9.0

TODO: manually check how many trainable parameters in total

In [10]:
import torchmetrics

In [11]:
def train2(model, optimizer, criterion, metric, train_loader, valid_loader,
               n_epochs):
    history = {"train_losses": [], "train_metrics": [], "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.
        metric.reset()
        for X_batch, y_batch in train_loader:
            model.train()
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            ##TODO: compute loss and add to total_loss

            total_loss
            ##TODO: finish the rest THREE steps for training

            metric.update(y_pred, y_batch)
        mean_loss = total_loss / len(train_loader)
        history["train_losses"].append(mean_loss)
        history["train_metrics"].append(metric.compute().item())
        history["valid_metrics"].append(
            evaluate_tm(model, valid_loader, metric).item())
        print(f"Epoch {epoch + 1}/{n_epochs}, "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.4f}, "
              f"valid metric: {history['valid_metrics'][-1]:.4f}")
    return history

In [12]:
def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()  # reset the metric at the beginning
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            ##TODO: check the prediction for X_batch

            metric.update(y_pred, y_batch)  # update it at each iteration
    return metric.compute()

In [13]:
torch.manual_seed(42)
#covtype_model.to(device)

for learning_rate in [0.16, 0.08, 0.04, 0.02, 0.01, 0.005]:
    n_epochs = 15
    optimizer = torch.optim.SGD(covtype_model.parameters(), lr=learning_rate)
    criterion = ##TODO: which loss criterion should we use?
    metric = torchmetrics.Accuracy(task="multiclass",
                                   num_classes=n_classes).to(device)
    history = ##TODO: call train2 function for training
##TODO: check the performance on testing data by calling evaluate_tm function

Epoch 1/15, train loss: 0.6336, train metric: 0.7344, valid metric: 0.7634
Epoch 2/15, train loss: 0.5142, train metric: 0.7788, valid metric: 0.8033
Epoch 3/15, train loss: 0.4556, train metric: 0.8048, valid metric: 0.8185
Epoch 4/15, train loss: 0.4120, train metric: 0.8258, valid metric: 0.8330
Epoch 5/15, train loss: 0.3804, train metric: 0.8406, valid metric: 0.8235
Epoch 6/15, train loss: 0.3541, train metric: 0.8525, valid metric: 0.8572
Epoch 7/15, train loss: 0.3313, train metric: 0.8634, valid metric: 0.8653
Epoch 8/15, train loss: 0.3159, train metric: 0.8695, valid metric: 0.8751
Epoch 9/15, train loss: 0.2997, train metric: 0.8771, valid metric: 0.8688
Epoch 10/15, train loss: 0.2880, train metric: 0.8814, valid metric: 0.8838
Epoch 11/15, train loss: 0.2765, train metric: 0.8862, valid metric: 0.8857
Epoch 12/15, train loss: 0.2668, train metric: 0.8905, valid metric: 0.8819
Epoch 13/15, train loss: 0.2587, train metric: 0.8942, valid metric: 0.8933
Epoch 14/15, train loss: 0.2505, train metric: 0.8976, valid metric: 0.8953
Epoch 15/15, train loss: 0.2429, train metric: 0.9008, valid metric: 0.8977
Epoch 1/15, train loss: 0.2037, train metric: 0.9180, valid metric: 0.9135
Epoch 2/15, train loss: 0.1982, train metric: 0.9199, valid metric: 0.9183
Epoch 3/15, train loss: 0.1949, train metric: 0.9212, valid metric: 0.9146
Epoch 4/15, train loss: 0.1919, train metric: 0.9225, valid metric: 0.9146
Epoch 5/15, train loss: 0.1892, train metric: 0.9235, valid metric: 0.9173
Epoch 6/15, train loss: 0.1870, train metric: 0.9241, valid metric: 0.9151
Epoch 7/15, train loss: 0.1844, train metric: 0.9253, valid metric: 0.9132
Epoch 8/15, train loss: 0.1826, train metric: 0.9262, valid metric: 0.9205
Epoch 9/15, train loss: 0.1802, train metric: 0.9271, valid metric: 0.9230
Epoch 10/15, train loss: 0.1794, train metric: 0.9277, valid metric: 0.9194
Epoch 11/15, train loss: 0.1766, train metric: 0.9286, valid metric: 0.9268
Epoch 12/15, train loss: 0.1751, train metric: 0.9293, valid metric: 0.9281
Epoch 13/15, train loss: 0.1737, train metric: 0.9298, valid metric: 0.9224
Epoch 14/15, train loss: 0.1715, train metric: 0.9307, valid metric: 0.9265
Epoch 15/15, train loss: 0.1705, train metric: 0.9308, valid metric: 0.9238
Epoch 1/15, train loss: 0.1459, train metric: 0.9421, valid metric: 0.9374
Epoch 2/15, train loss: 0.1431, train metric: 0.9429, valid metric: 0.9368
Epoch 3/15, train loss: 0.1422, train metric: 0.9433, valid metric: 0.9371
Epoch 4/15, train loss: 0.1410, train metric: 0.9434, valid metric: 0.9365
Epoch 5/15, train loss: 0.1399, train metric: 0.9440, valid metric: 0.9367
Epoch 6/15, train loss: 0.1389, train metric: 0.9442, valid metric: 0.9367
Epoch 7/15, train loss: 0.1381, train metric: 0.9448, valid metric: 0.9354
Epoch 8/15, train loss: 0.1374, train metric: 0.9452, valid metric: 0.9372
Epoch 9/15, train loss: 0.1366, train metric: 0.9451, valid metric: 0.9381
Epoch 10/15, train loss: 0.1360, train metric: 0.9454, valid metric: 0.9369
Epoch 11/15, train loss: 0.1352, train metric: 0.9459, valid metric: 0.9379
Epoch 12/15, train loss: 0.1344, train metric: 0.9463, valid metric: 0.9403
Epoch 13/15, train loss: 0.1336, train metric: 0.9467, valid metric: 0.9378
Epoch 14/15, train loss: 0.1331, train metric: 0.9466, valid metric: 0.9400
Epoch 15/15, train loss: 0.1323, train metric: 0.9468, valid metric: 0.9394
Epoch 1/15, train loss: 0.1186, train metric: 0.9533, valid metric: 0.9443
Epoch 2/15, train loss: 0.1171, train metric: 0.9540, valid metric: 0.9452
Epoch 3/15, train loss: 0.1162, train metric: 0.9544, valid metric: 0.9452
Epoch 4/15, train loss: 0.1158, train metric: 0.9545, valid metric: 0.9441
Epoch 5/15, train loss: 0.1153, train metric: 0.9547, valid metric: 0.9451
Epoch 6/15, train loss: 0.1147, train metric: 0.9548, valid metric: 0.9416
Epoch 7/15, train loss: 0.1144, train metric: 0.9549, valid metric: 0.9465
Epoch 8/15, train loss: 0.1139, train metric: 0.9550, valid metric: 0.9455
Epoch 9/15, train loss: 0.1134, train metric: 0.9550, valid metric: 0.9463
Epoch 10/15, train loss: 0.1129, train metric: 0.9556, valid metric: 0.9457
Epoch 11/15, train loss: 0.1127, train metric: 0.9556, valid metric: 0.9466
Epoch 12/15, train loss: 0.1120, train metric: 0.9556, valid metric: 0.9465
Epoch 13/15, train loss: 0.1121, train metric: 0.9555, valid metric: 0.9445
Epoch 14/15, train loss: 0.1114, train metric: 0.9560, valid metric: 0.9442
Epoch 15/15, train loss: 0.1111, train metric: 0.9561, valid metric: 0.9472
Epoch 1/15, train loss: 0.1037, train metric: 0.9600, valid metric: 0.9496
Epoch 2/15, train loss: 0.1029, train metric: 0.9602, valid metric: 0.9498
Epoch 3/15, train loss: 0.1027, train metric: 0.9603, valid metric: 0.9496
Epoch 4/15, train loss: 0.1025, train metric: 0.9602, valid metric: 0.9490
Epoch 5/15, train loss: 0.1020, train metric: 0.9605, valid metric: 0.9497
Epoch 6/15, train loss: 0.1018, train metric: 0.9607, valid metric: 0.9498
Epoch 7/15, train loss: 0.1016, train metric: 0.9607, valid metric: 0.9500
Epoch 8/15, train loss: 0.1012, train metric: 0.9609, valid metric: 0.9502
Epoch 9/15, train loss: 0.1010, train metric: 0.9610, valid metric: 0.9496
Epoch 10/15, train loss: 0.1008, train metric: 0.9608, valid metric: 0.9496
Epoch 11/15, train loss: 0.1006, train metric: 0.9609, valid metric: 0.9501
Epoch 12/15, train loss: 0.1003, train metric: 0.9611, valid metric: 0.9499
Epoch 13/15, train loss: 0.0999, train metric: 0.9613, valid metric: 0.9508
Epoch 14/15, train loss: 0.1000, train metric: 0.9610, valid metric: 0.9503
Epoch 15/15, train loss: 0.0996, train metric: 0.9614, valid metric: 0.9510
Epoch 1/15, train loss: 0.0960, train metric: 0.9634, valid metric: 0.9520
Epoch 2/15, train loss: 0.0955, train metric: 0.9637, valid metric: 0.9510
Epoch 3/15, train loss: 0.0954, train metric: 0.9636, valid metric: 0.9523
Epoch 4/15, train loss: 0.0952, train metric: 0.9639, valid metric: 0.9520
Epoch 5/15, train loss: 0.0951, train metric: 0.9639, valid metric: 0.9513
Epoch 6/15, train loss: 0.0949, train metric: 0.9640, valid metric: 0.9522
Epoch 7/15, train loss: 0.0948, train metric: 0.9638, valid metric: 0.9529
Epoch 8/15, train loss: 0.0947, train metric: 0.9642, valid metric: 0.9520
Epoch 9/15, train loss: 0.0945, train metric: 0.9639, valid metric: 0.9525
Epoch 10/15, train loss: 0.0943, train metric: 0.9641, valid metric: 0.9523
Epoch 11/15, train loss: 0.0942, train metric: 0.9640, valid metric: 0.9524
Epoch 12/15, train loss: 0.0941, train metric: 0.9640, valid metric: 0.9527
Epoch 13/15, train loss: 0.0940, train metric: 0.9642, valid metric: 0.9522
Epoch 14/15, train loss: 0.0939, train metric: 0.9643, valid metric: 0.9520
Epoch 15/15, train loss: 0.0937, train metric: 0.9644, valid metric: 0.9529

tensor(0.9503)